services:
  app:
    image: mohbaba12/helloworld
    environment:
#      - DATABASE_URL=postgresql://user:password@db:5432/usermanager_database
#      - jdbc:postgresql://db:5432/usermanager_database
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/hello_world
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    environment:
      POSTGRES_DB: helloworld_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
