---
name: Deploy Dockerhub
on:
  push:
    branches:
      - in-dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/checkout@v2
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t mohbaba12/helloworld:latest .
      - name: Push Docker image to Docker Hub
        run: docker push mohbaba12/helloworld:latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Run Docker Compose On Instance
        env:
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
          EC2_KEY_PAIR: ${{ secrets.EC2_KEY_PAIR }}
        run: |
          echo "${{ secrets.EC2_KEY_PAIR }}" > ec2-key.pem
          chmod 400 ec2-key.pem
            ssh -i ec2-key.pem ubuntu@18.215.168.182 << 'EOF'
            sudo docker pull mohbaba12/helloworld:latest
            sudo docker-compose up --build
          EOF
